/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.ButtonGroup;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.table.TableModel;

/**
 *
 * @author WINDOWS 10
 */
public class GUI extends javax.swing.JFrame {

    private Object model;



    /**
     * Creates new form GUI
     */
    public GUI() { //konstruktor
         koneksi konek = new koneksi();
        konek.koneksi();
        initComponents();
        this.setTitle("Pendaftaran UKM");
        this.setLocationRelativeTo(this);
        this.StatusKoneksi.setText(konek.statusKoneksi);

       
        //this.StatusKoneksi.setText(konek.statusKoneksi);

        ButtonGroup bG = new ButtonGroup();
        bG.add(INlpm);
        bG.add(INpramuka);
        bG.add(INwidyakirana);
        bG.add(INpn);
        bG.add(INbadminton);
        bG.add(INmapala);
        
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        INlpm = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        INpramuka = new javax.swing.JRadioButton();
        INwidyakirana = new javax.swing.JRadioButton();
        INpn = new javax.swing.JRadioButton();
        INbadminton = new javax.swing.JRadioButton();
        INmapala = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        INnama = new javax.swing.JTextField();
        INnim = new javax.swing.JTextField();
        INprodi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datamhs = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        StatusKoneksi = new javax.swing.JTextField();
        hapusdata = new javax.swing.JButton();
        resetdata = new javax.swing.JButton();
        ubahdata = new javax.swing.JButton();
        pencariandatamhs = new javax.swing.JComboBox<>();
        pencarian = new javax.swing.JTextField();
        caridata = new javax.swing.JButton();
        selesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        INlpm.setText("LPM Bhanu Tirta");
        INlpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INlpmActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DAFTAR UKM");

        INpramuka.setText("Pramuka");

        INwidyakirana.setText("Widya Kirana");
        INwidyakirana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INwidyakiranaActionPerformed(evt);
            }
        });

        INpn.setText("Pagar Nusa");
        INpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INpnActionPerformed(evt);
            }
        });

        INbadminton.setText("Badminton");

        INmapala.setText("MAPALA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(INpramuka))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(INlpm))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(INwidyakirana))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(INpn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(INbadminton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(INmapala)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(INlpm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(INpramuka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INwidyakirana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INpn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INbadminton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INmapala)
                .addGap(34, 34, 34))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PENDAFTARAN");

        jLabel3.setText("NAMA");

        jLabel4.setText("NIM");

        INnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INnamaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("PRODI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE))
                            .addComponent(INnama)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(INprodi)
                            .addComponent(INnim))))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(112, 112, 112))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(INnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("UKM", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datamhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAMA", "NIM", "PRODI", "UKM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        datamhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datamhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datamhs);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Status Koneksi");

        StatusKoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusKoneksiActionPerformed(evt);
            }
        });

        hapusdata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapusdata.setText("Hapus");
        hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusdataActionPerformed(evt);
            }
        });

        resetdata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetdata.setText("Refresh");
        resetdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetdataActionPerformed(evt);
            }
        });

        ubahdata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ubahdata.setText("Ubah");
        ubahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahdataActionPerformed(evt);
            }
        });

        pencariandatamhs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pencariandatamhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pencarian-", "NAMA", "NIM", "PRODI", "UKM" }));
        pencariandatamhs.setToolTipText("");
        pencariandatamhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencariandatamhsActionPerformed(evt);
            }
        });

        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        caridata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caridata.setText("Cari");
        caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caridataActionPerformed(evt);
            }
        });

        selesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selesai.setText("Selesai");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pencariandatamhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetdata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatusKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selesai)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencariandatamhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caridata)
                    .addComponent(resetdata)
                    .addComponent(ubahdata)
                    .addComponent(hapusdata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(StatusKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selesai))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Statement pst;
    ResultSet rs;

    public void table() {
        koneksi konek = new koneksi();
        konek.koneksi();
        try {
            String sql = "select * from datamhs";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            datamhs.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void selectByNAMA(String nama){
        koneksi konek = new koneksi();
        konek.koneksi();
        
        try{
            String sql = "select * from datamhs where nama like '%" + nama + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            datamhs.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void selectByNIM(String nim){
        koneksi konek = new koneksi();
        konek.koneksi();
        
        try{
            String sql = "select * from datamhs where nim like '%" + nim + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            datamhs.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void selectByPRODI(String prodi){
        koneksi konek = new koneksi();
        konek.koneksi();
        
        try{
            String sql = "select * from datamhs where prodi like '%" + prodi + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            datamhs.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void selectByUKM(String ukm){
        koneksi konek = new koneksi();
        konek.koneksi();
        
        try{
            String sql = "select * from datamhs where ukm like '%" + ukm + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            datamhs.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void INpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INpnActionPerformed

    private void INwidyakiranaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INwidyakiranaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INwidyakiranaActionPerformed

    private void StatusKoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusKoneksiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StatusKoneksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String ukm = "";
        if (INlpm.isSelected()) {
            ukm = "LPM Bhanu Tirta";
        } else if (INwidyakirana.isSelected()) {
            ukm = "Widya Kirana";
        } else if (INpn.isSelected()) {
            ukm = "Pagar Nusa";
        } else if (INbadminton.isSelected()) {
            ukm = "Badminton";
        } else if (INmapala.isSelected()) {
            ukm = "MAPALA";
        } else if (INpramuka.isSelected()) {
            ukm = "Pramuka";
        }
        
        Insert in = new Insert();
        String nama = INnama.getText();
        String nim = INnim.getText();
        String prodi = INprodi.getText();
        in.insert(nama, nim, prodi, ukm);
        
        table();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void INlpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INlpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INlpmActionPerformed

    private void datamhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datamhsMouseClicked
        // TODO add your handling code here:
        int selectedRow = datamhs.getSelectedRow();
        
        TableModel model = datamhs.getModel();
        INnama.setText(model.getValueAt(selectedRow, 0).toString());
        INnim.setText(model.getValueAt(selectedRow, 1).toString());
        INprodi.setText(model.getValueAt(selectedRow, 2).toString());
        String ukm = model.getValueAt(selectedRow, 3).toString();
            if(ukm.equals("LPM Bhanu Tirta")){
                INlpm.setSelected(true);
            } else if (ukm.equals("Pramuka")){
                INpramuka.setSelected(true);
            } else if (ukm.equals("Widya Kirana")){
                INwidyakirana.setSelected(true);
            } else if (ukm.equals("Pagar Nusa")){
                INpn.setSelected(true);
            } else if (ukm.equals("Badminton")){
                INbadminton.setSelected(true);
            } else if (ukm.equals("MAPALA")){
                INmapala.setSelected(true);
            }
       
    }//GEN-LAST:event_datamhsMouseClicked

    private void hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusdataActionPerformed
        // TODO add your handling code here:
        koneksi konek = new koneksi();
        konek.koneksi();
        Delete del = new Delete();
        del.delete(INnama.getText());
        
        table();
    }//GEN-LAST:event_hapusdataActionPerformed

    private void resetdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetdataActionPerformed
        // TODO add your handling code here:
        INnama.setText("");
        INnim.setText("");
        INprodi.setText("");

        ButtonGroup bG = new ButtonGroup();
        bG.add(INlpm);
        bG.add(INpramuka);
        bG.add(INwidyakirana);
        bG.add(INpn);
        bG.add(INbadminton);
        bG.add(INmapala);
        bG.clearSelection();
        
        table();

    }//GEN-LAST:event_resetdataActionPerformed

    private void ubahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahdataActionPerformed
        // TODO add your handling code here:
        koneksi konek = new koneksi();
        konek.koneksi();
                                                                        
        Update up = new Update();
        String nama = INnama.getText();
        String nim = INnim.getText();
        String prodi = INprodi.getText();
        String ukm = "";
        
        if (INlpm.isSelected()) {
            ukm = "LPM Bhanu Tirta";
        } else if (INwidyakirana.isSelected()) {
            ukm = "Widya Kirana";
        } else if (INpn.isSelected()) {
            ukm = "Pagar Nusa";
        } else if (INbadminton.isSelected()) {
            ukm = "Badminton";
        } else if (INmapala.isSelected()) {
            ukm = "MAPALA";
        } else if (INpramuka.isSelected()) {
            ukm = "Pramuka";
        }
        up.update(nama, nim, prodi, ukm );
        
        table();
        
    }//GEN-LAST:event_ubahdataActionPerformed

    private void pencariandatamhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencariandatamhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencariandatamhsActionPerformed

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pencarianActionPerformed

    private void caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caridataActionPerformed
        // TODO add your handling code here:
        if(pencariandatamhs.getSelectedIndex() == 1){
            selectByNAMA(pencarian.getText());
        } else if (pencariandatamhs.getSelectedIndex() == 2){
            selectByNIM(pencarian.getText());
        } else if (pencariandatamhs.getSelectedIndex() == 3){
            selectByPRODI(pencarian.getText());
        } else if (pencariandatamhs.getSelectedIndex() == 4){
            
            String Ukm = "";
            if(INlpm.isSelected()){
                Ukm = "LPM Bhanu Tirta";
            }  else if (INwidyakirana.isSelected()) {
                Ukm = "Widya Kirana";
            } else if (INpn.isSelected()) {
                Ukm = "Pagar Nusa";
            } else if (INbadminton.isSelected()) {
                Ukm = "Badminton";
            } else if (INmapala.isSelected()) {
                Ukm = "MAPALA";
            } else if (INpramuka.isSelected()) {
                Ukm = "Pramuka";
            } 
            
            selectByUKM(pencarian.getText());
            
      } else{
            table();
        }  
        
    }//GEN-LAST:event_caridataActionPerformed

    private void INnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INnamaActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
        System.exit(0);s
    }//GEN-LAST:event_selesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton INbadminton;
    private javax.swing.JRadioButton INlpm;
    private javax.swing.JRadioButton INmapala;
    private javax.swing.JTextField INnama;
    private javax.swing.JTextField INnim;
    private javax.swing.JRadioButton INpn;
    private javax.swing.JRadioButton INpramuka;
    private javax.swing.JTextField INprodi;
    private javax.swing.JRadioButton INwidyakirana;
    private javax.swing.JTextField StatusKoneksi;
    private javax.swing.JButton caridata;
    private javax.swing.JTable datamhs;
    private javax.swing.JButton hapusdata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pencarian;
    private javax.swing.JComboBox<String> pencariandatamhs;
    private javax.swing.JButton resetdata;
    private javax.swing.JButton selesai;
    private javax.swing.JButton ubahdata;
    // End of variables declaration//GEN-END:variables
}
